name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  env: 
    NODE_VERSION: 18

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Code Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Install Playwright Browsers
      run: pnpm install playwright --with-deps
      
    - name: Run Playwright tests
      run: pnpm exec playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30