name: Run Playwright
on: 
  push:
    branches: [main]
  pull_request: 
    branches: [main]

env: 
  NODE_VERSION: 18

jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: PNPM Caching
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile	

      - name: Install PLaywright + Run PLaywright
        run: pnpm install playwright --with-deps
        run: pnpm install playwright test
        uses: actions/upload-artifact@v3
          if: always()
          with: 
           name: playwright-report
           path: playwright-report/
           retention-days: 30